[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Chris Lam <christopher.lam@grainger.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.19"
